# Generated by Django 4.1.4 on 2023-07-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branches', to='users.branch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='screens',
            field=models.ManyToManyField(blank=True, related_name='screens', to='users.screenaccess'),
        ),
    ]
