# Generated by Django 4.1.4 on 2023-08-02 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_homepagemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagemessage',
            name='sequence_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepagemessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
