# Generated by Django 4.1.4 on 2023-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_homepagemessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_sales_manager',
            field=models.BooleanField(default=False, help_text='Note: If this is True, is_sales must also be True.'),
        ),
    ]
