# Generated by Django 4.1.4 on 2024-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sitemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_archieve',
            field=models.BooleanField(default=False),
        ),
    ]
