# Generated by Django 3.2.10 on 2024-09-23 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_userprofile_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_archieve',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_dmd',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_ho',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_nib',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_sales',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_sales_manager',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
