# Generated by Django 3.2.10 on 2024-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_productgroupmaster_is_po_mo_mandatory'),
        ('users', '0014_auto_20240923_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor',
            field=models.ManyToManyField(blank=True, related_name='vendor_masters', to='masters.VendorMasters'),
        ),
    ]
