# Generated by Django 3.2.10 on 2025-03-17 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isVendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
