# Generated by Django 4.1.7 on 2024-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormasters',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendormasters',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
