# Generated by Django 4.1.7 on 2024-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_vendormasters_email_vendormasters_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=100)),
                ('group_code', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('packing_name', models.CharField(db_index=True, max_length=255)),
                ('fixed', models.CharField(db_index=True, max_length=10)),
                ('no_of_packages', models.CharField(max_length=150)),
                ('status', models.BooleanField(db_index=True, default='False')),
                ('wh_team_name', models.CharField(db_index=True, max_length=255)),
                ('source_of_supply', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendors', models.ManyToManyField(blank=True, related_name='vendors', to='masters.vendormasters')),
            ],
            options={
                'unique_together': {('product', 'group_code')},
            },
        ),
    ]
