# Generated by Django 4.1.7 on 2024-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_productgroupmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupmaster',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendormasters',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
    ]
