# Generated by Django 4.1.7 on 2024-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_productgroupmaster_s_no_vendormasters_s_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupmaster',
            name='qr_type',
            field=models.CharField(db_index=True, default='Type-1', max_length=50),
        ),
    ]
