# Generated by Django 4.1.7 on 2024-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_productgroupmaster_qr_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTypeMasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_type', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.BooleanField(db_index=True, default='False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
