# Generated by Django 4.1.7 on 2024-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_vehicletypemasters'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupmaster',
            name='qr_code_scanning',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgroupmaster',
            name='use_qr_code_scanning',
            field=models.BooleanField(default=False),
        ),
    ]
