# Generated by Django 3.2.10 on 2025-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_productgroupmaster_is_po_mo_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormasters',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productgroupmaster',
            name='no_of_packages',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProductGroupPackageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=100)),
                ('group_code', models.CharField(db_index=True, max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('no_of_packages', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('product', 'group_code', 'qty')},
            },
        ),
    ]
