# Generated by Django 4.1.7 on 2024-07-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('group_code', models.CharField(max_length=50)),
                ('part_description', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('project_no', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('po_mo_no', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
        ),
    ]
