# Generated by Django 4.1.7 on 2024-07-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_ebom_created_at_ebom_status_ebom_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebom',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebom',
            name='group_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ebom',
            name='project_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebom',
            name='project_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
