# Generated by Django 4.1.7 on 2024-07-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_productgroupmaster_s_no_vendormasters_s_no'),
        ('project', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(db_index=True, max_length=50)),
                ('part_description', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('po_mo_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.vendormasters')),
            ],
        ),
    ]
