# Generated by Django 4.1.7 on 2024-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_project_no_part_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
