# Generated by Django 4.1.7 on 2024-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_part_wht_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qr_type',
            field=models.CharField(db_index=True, default='Type-1', max_length=50),
        ),
    ]
