# Generated by Django 4.1.7 on 2024-07-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_partlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlog',
            name='updated_at',
        ),
    ]
