# Generated by Django 4.1.7 on 2024-07-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_partlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_ecn',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='partlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
