# Generated by Django 4.1.7 on 2024-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_part_is_ecn_partlog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='vehicle_status',
            field=models.IntegerField(default=0),
        ),
    ]
