# Generated by Django 4.1.7 on 2024-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_part_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='load_in_truck_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='truck_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
