# Generated by Django 4.1.7 on 2024-07-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_part_load_in_truck_time_alter_part_truck_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_package_mapping',
            field=models.TextField(blank=True, default='', max_length=800, null=True),
        ),
    ]
