# Generated by Django 4.1.7 on 2024-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_part_part_package_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qr_code_scanning',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='use_qr_code_scanning',
            field=models.BooleanField(default=False),
        ),
    ]
