# Generated by Django 4.1.7 on 2024-08-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_part_scanned_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(db_index=True, max_length=200)),
                ('packAgeIndex', models.IntegerField()),
                ('partsSelectedIndex', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.part')),
            ],
        ),
    ]
