# Generated by Django 4.1.7 on 2024-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_packageindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageindex',
            name='ProjectNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
