# Generated by Django 4.1.7 on 2024-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_packageindex_projectno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('project', 'part_number', 'group_code')},
        ),
        migrations.AddField(
            model_name='part',
            name='is_po_mo_mandatory',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
