# Generated by Django 4.1.7 on 2024-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_part_unique_together_part_is_po_mo_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageindex',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
