# Generated by Django 4.1.7 on 2024-08-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_activitylog_project_alter_partlog_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='part',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='project.project'),
        ),
    ]
