# Generated by Django 4.1.7 on 2024-09-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_part_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='project.vehicle'),
        ),
    ]
