# Generated by Django 4.1.7 on 2024-09-06 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_remove_part_vehicle_part_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.vehicle'),
        ),
    ]
