# Generated by Django 4.1.7 on 2024-09-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0037_alter_part_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_part', to='project.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='info', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.vehicle')),
            ],
        ),
    ]
