# Generated by Django 3.2.10 on 2024-09-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_productgroupmaster_is_po_mo_mandatory'),
        ('project', '0038_alter_part_vehicle_vehiclelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masters.vendormasters'),
        ),
    ]
