# Generated by Django 3.2.10 on 2024-12-15 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_alter_partlog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='distribution_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributon_vehicle_part', to='project.vehicle'),
        ),
        migrations.AddField(
            model_name='part',
            name='distribution_vehicle_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='destination',
            field=models.IntegerField(db_index=True, default=0, help_text='0: Project Site , 1:  Destination Center'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(default=0, help_text='0: Active, 1: Shipped, 2: Cancelled'),
        ),
    ]
