# Generated by Django 3.2.10 on 2024-12-15 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20241215_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageindex',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_index', to='project.part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='distribution_vehicle_status',
            field=models.IntegerField(default=0, help_text=" 0: 'No Truck Data', 1: 'Truck Data Loaded', 2: 'Partially Loaded', 3: 'Un Loaded', 4: 'Loaded'"),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.IntegerField(default=0, help_text=" 0: 'To Approve', 1: 'Approved', 2: 'WIP', 3: 'WIP - Partially Loaded', 4: 'Item Packed', 10: 'Delivered', 99: 'Item Not Available', 100: '100% Completed'"),
        ),
        migrations.AlterField(
            model_name='part',
            name='vehicle_status',
            field=models.IntegerField(default=0, help_text=" 0: 'No Truck Data', 1: 'Truck Data Loaded', 2: 'Partially Loaded', 3: 'Un Loaded', 4: 'Loaded'"),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor_status',
            field=models.IntegerField(default=0, help_text="  0: 'Pending', 1: 'QR Generated', 2: 'Package Allocation Done', 3: 'Packing Slip Generated'"),
        ),
    ]
