# Generated by Django 3.2.10 on 2025-03-17 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_auto_20250317_2259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0043_auto_20241215_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='accepted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='part',
            name='assigned_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='part',
            name='qc_passed',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='received_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_shipped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor_status',
            field=models.IntegerField(default=0, help_text="-3:Pending for acceptance,-2:Rejected by Vendor,  0: 'Pending', 1: 'QR Generated', 2: 'Package Allocation Done', 3: 'Packing Slip Generated'"),
        ),
        migrations.CreateModel(
            name='VendorRejectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrd', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_on', models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 17, 17, 29, 18, 224392, tzinfo=utc), null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_history', to='project.part')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.vendormasters')),
            ],
        ),
    ]
