# Generated by Django 3.2.10 on 2025-03-18 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_alter_vendorrejectionhistory_assigned_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrejectionhistory',
            name='assigned_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 18, 0, 16, 51, 883614, tzinfo=utc), null=True),
        ),
    ]
