# Generated by Django 3.2.10 on 2025-03-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_alter_vendorrejectionhistory_assigned_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrejectionhistory',
            name='assigned_on',
        ),
        migrations.AddField(
            model_name='vendorrejectionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
