# Generated by Django 3.2.10 on 2024-10-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_operation', '0004_auto_20241017_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_logs', to='first_operation.batch'),
        ),
    ]
