# Generated by Django 3.2.10 on 2024-10-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_operation', '0007_auto_20241020_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitems',
            name='nesting_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='batchitems',
            name='thickness',
            field=models.CharField(max_length=25),
        ),
    ]
