# Generated by Django 3.2.10 on 2024-10-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_operation', '0008_auto_20241020_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitems',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_operation.batch'),
        ),
    ]
