# Generated by Django 3.2.10 on 2024-10-21 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_operation', '0009_alter_batchitems_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitems',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items_set', to='first_operation.batch'),
        ),
    ]
