# Generated by Django 3.2.10 on 2024-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_operation', '0011_auto_20241029_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitems',
            name='repeating_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='batchnestingitems',
            name='batchNo',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchnestingitems',
            name='material',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchnestingitems',
            name='sheetThickness',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
